name: Continuous Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Clone @api3/ois
        uses: actions/checkout@master
      - name: Check hyperlinks
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: .github/workflows/mlc_config.json

  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone @api3/ois
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test

  required-checks-passed:
    name: All required checks passed
    runs-on: ubuntu-latest
    needs: [lint-test]
    steps:
      - run: exit 0
